export const groups = [
  { slug: 'diabetes', icon: '🌿', name: 'Diabetes Support Group', desc: 'Type 1 & Type 2 Diabetic patients' },
  { slug: 'pregnancy', icon: '🤰', name: 'Pregnancy Circle', desc: 'Expecting mothers, new moms' },
  { slug: 'cardiac-care', icon: '❤️', name: 'Cardiac Care', desc: 'Heart patients post-surgery or diagnosis' },
  { slug: 'mental-health', icon: '🧠', name: 'Mental Health Matters', desc: 'Depression, anxiety, and therapy support' },
  { slug: 'child-health', icon: '👶', name: 'Child Health Forum', desc: 'Parents with newborn/children' },
  { slug: 'senior-health', icon: '🧓', name: 'Senior Health Hub', desc: 'Elderly patients managing multiple issues' },
  { slug: 'cancer', icon: '🧬', name: 'Cancer Fighters Club', desc: 'Cancer awareness & treatment support' },
  { slug: 'bone-joint', icon: '🦴', name: 'Bone & Joint Support', desc: 'Orthopedic care and rehab' },
  { slug: 'eye-health', icon: '👁️', name: 'Vision & Eye Health', desc: 'Eye care and surgery support' },
  { slug: 'hearing', icon: '👂', name: 'Hearing Support Group', desc: 'Support for hearing loss and hearing aids' },
  { slug: 'lung-health', icon: '🫁', name: 'Breathing & Lung Health', desc: 'Asthma, COPD, and respiratory support' },
  { slug: 'dental-care', icon: '🦷', name: 'Dental Care Group', desc: 'Oral hygiene and dental treatment help' },
  { slug: 'general-health', icon: '⚕️', name: 'General Health & Wellness', desc: 'Tips for daily health and fitness' },
  { slug: 'dermatology', icon: '🧴', name: 'Skin & Dermatology Care', desc: 'Skincare issues, acne, eczema etc.' },
  { slug: 'nutrition', icon: '🧃', name: 'Nutrition & Diet Circle', desc: 'Healthy eating and diet planning' },
  { slug: 'yoga-lifestyle', icon: '🧘', name: 'Yoga & Lifestyle Healing', desc: 'Yoga, meditation, stress relief' },
  { slug: 'infection-recovery', icon: '🦠', name: 'Infection Recovery Group', desc: 'Flu, COVID-19, and infection recovery' },
  { slug: 'weight-loss', icon: '📉', name: 'Weight Loss Warriors', desc: 'Weight loss and fitness transformation' },
  { slug: 'fitness-strength', icon: '📈', name: 'Fitness & Strength Hub', desc: 'Workout plans and fitness advice' },
  { slug: 'womens-health', icon: '🩺', name: 'Women’s Health Forum', desc: 'PCOS, pregnancy, menopause support' },
  { slug: 'mens-health', icon: '👨‍⚕️', name: 'Men’s Health Talk', desc: 'Prostate, testosterone, fitness etc.' },
  { slug: 'family-health', icon: '👨‍👩‍👧‍👦', name: 'Family Health Corner', desc: 'Health tips for families and children' },
  { slug: 'thyroid', icon: '🧫', name: 'Thyroid & Hormone Help', desc: 'Hypo/Hyperthyroidism, hormones' },
  { slug: 'bp-cholesterol', icon: '🧪', name: 'Blood Pressure & Cholesterol', desc: 'Heart health, BP & cholesterol care' },
  { slug: 'med-reminder', icon: '💊', name: 'Medicine Reminder Group', desc: 'Reminders and medication tracking' },
  { slug: 'foot-care', icon: '👣', name: 'Foot Care & Diabetes Foot Talk', desc: 'Foot ulcers, neuropathy care' },
  { slug: 'mobility-rehab', icon: '🦽', name: 'Mobility & Rehab Support', desc: 'Stroke, injury, and physical rehab' },
  { slug: 'sleep-disorders', icon: '😴', name: 'Sleep Disorders & Tips', desc: 'Insomnia, sleep apnea support' },
  { slug: 'teen-health', icon: '🚸', name: 'Teen Health Awareness', desc: 'Puberty, growth, mental health' },
  { slug: 'infertility', icon: '🚼', name: 'Infertility & IVF Journey', desc: 'Support for couples undergoing IVF' },
  { slug: 'ask-doctor', icon: '🧑‍⚕️', name: 'Ask a Doctor (General)', desc: 'General health Q&A with doctors' },
  { slug: 'post-surgery', icon: '🧭', name: 'Post-Surgery Recovery Group', desc: 'Healing and post-op care tips' },
  { slug: 'vaccination', icon: '💉', name: 'Vaccination Awareness Hub', desc: 'Child, adult, and travel vaccines' },
  { slug: 'medical-travel', icon: '🧳', name: 'Medical Travel & Support', desc: 'Health travel and hospital info' },
  { slug: 'education-resources', icon: '📓', name: 'Health Education & Resources', desc: 'Medical tips and educational content' },
  { slug: 'fun-talks', icon: '🎉', name: 'Fun Talks & Stress Relief', desc: 'Light-hearted chats and humor to unwind and reduce stress' }
];
